# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Franco Trento"
description: "Arte Moderna Concettuale - Portfolio e Mostre"
baseurl: ""
url: "https://francotrento.com"

author:
  name: "Franco Trento"
  email: "info@francotrento.com"
  bio: "Artista di arte moderna concettuale"

collections:
  portfolio:
    output: true
    permalink: "/portfolio/:title/"
  mostre:
    output: true
    permalink: "/mostre/:title/"

plugins:
  - jekyll-feed
  - jekyll-sitemap

navigation:
  - title: "Home"
    url: "/"
  - title: "Portfolio"
    url: "/portfolio/"
  - title: "Mostre"
    url: "/mostre/"
  - title: "Contatti"
    url: "https://forms.gle/Pv5PoBbQUStbxdu5A"

faq:
  - question: "Posso acquistare direttamente le opere di Franco Trento?"
    answer: "Le opere di Franco Trento sono disponibili per collezionisti e gallerie selezionate. Se sei interessato, <a href='https://forms.gle/Pv5PoBbQUStbxdu5A' target='_blank' class='text-black'>contattaci</a> direttamente per discutere disponibilità e modalità d’acquisto."
  - question: "Accettate commissioni per opere su misura?"
    answer: "Franco Trento realizza opere personalizzate solo su progetti che rispettano la sua visione artistica. Se hai un’idea che pensi possa allinearsi con il suo stile, <a href='https://forms.gle/Pv5PoBbQUStbxdu5A' target='_blank' class='text-black'>contattaci</a> per una valutazione.."
  - question: "Sono un gallerista/curatore, posso esporre le opere di Franco Trento?"
    answer: "Siamo sempre aperti a collaborazioni con gallerie e curatori che vogliono valorizzare il lavoro di Franco Trento. Se sei interessato a una mostra o a una collaborazione, scrivici con la tua proposta."
  - question: "Posso intervistare Franco Trento o scrivere un articolo su di lui?"
    answer: "Siamo disponibili per interviste con giornalisti, blogger e critici d’arte seriamente interessati al suo lavoro. <a href='https://forms.gle/Pv5PoBbQUStbxdu5A' target='_blank' class='text-black'>Contattaci</a> con i dettagli della tua richiesta."
  - question: "Accettate proposte di partnership o sponsorizzazione?"
    answer: "Collaboriamo con brand e realtà che condividono valori affini al mondo dell’arte contemporanea. Se credi che la tua azienda o il tuo progetto possa creare valore reciproco, inviaci la tua proposta."
  - question: "Fate consulenze artistiche o valutazioni di opere?"
    answer: "No, il nostro focus è sulla produzione e diffusione delle opere di Franco Trento."
  - question: "Posso scrivervi per chiacchierare o chiedere consigli generici sull’arte?"
    answer: "No. Se sei un appassionato d’arte, ti invitiamo a seguire Franco Trento sui social e a visitare le sue mostre."

social:
  instagram: "https://www.instagram.com/francotrentoart"
  facebook: "https://www.facebook.com/francotrentoart"
  twitter: "https://twitter.com/francotrento"

permalink: "/:categories/:title/"
markdown: kramdown


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
